// What BWAPI believes StarCraft 1.16.1's memory looks like.
//
// Every value here is a promise about a process this program is not running in. The addresses are
// literals in BW/Offsets.h and no compiler can move them - but the *types* bound to those
// addresses are laid out by whatever compiler built the DLL, and if a layout moves by one byte
// then every field read through it lands on the wrong bytes of the real game. That failure is
// silent: the DLL builds, loads, and reports nonsense.
//
// So this dumps both halves - the address each BWDATA reference is bound to, and the size and
// alignment of every type mapped onto game memory - into a text file compared against a committed
// baseline. It is the same idea as bwapi-c2's GameData layout baseline, pointed at the other side
// of the boundary.
//
// It exists because this series retargeted the toolset off v141_xp and moved _WIN32_WINNT from
// Windows XP to Windows 7. Neither can move an address. Either could, in principle, move a
// layout - and the SDK types below (POINT, PALETTEENTRY, RECT) are the ones the _WIN32_WINNT
// change would reach first, which is why they are dumped alongside BWAPI's own.

// Offsets.h forward-declares CUnit, Bitmap, Font and friends and binds references to them, which
// is legal for an incomplete type and useless for sizeof. Every defining header is named here.
#include <BW/AIController.h>
#include <BW/Bitmap.h>
#include <BW/BWGame.h>
#include <BW/CBullet.h>
#include <BW/CImage.h>
#include <BW/COrder.h>
#include <BW/CSprite.h>
#include <BW/CThingy.h>
#include <BW/CUnit.h>
#include <BW/Dialog.h>
#include <BW/Font.h>
#include <BW/Offsets.h>
#include <BW/Path.h>
#include <BW/Pathing.h>
#include <BW/PositionUnitTarget.h>
#include <BW/Render.h>
#include <BW/Replay.h>
#include <BW/Structures.h>
#include <BW/Target.h>
#include <BW/TileSet.h>
#include <BW/TileType.h>
#include <BW/TriggerEngine.h>
#include <BW/UnitTarget.h>

#include <cstdio>
#include <cstdint>

#define DUMP_TYPE(T) \
  std::printf("type %-34s size %-8zu align %zu\n", #T, sizeof(T), alignof(T))

#define DUMP_ADDR(N) \
  std::printf("addr %-34s 0x%08X\n", #N, \
              static_cast<unsigned>(reinterpret_cast<std::uintptr_t>(&BW::BWDATA::N)))

int main()
{
  std::printf("# BWAPI view of StarCraft 1.16.1 memory\n");
  std::printf("# Generated by tests/bw_layout/bw_layout_dump.cpp - do not edit by hand.\n");
  std::printf("#\n");
  std::printf("# A diff here means the compiler changed what BWAPI thinks the game looks like.\n");
  std::printf("\n# --- types mapped onto game memory ---\n");

  DUMP_TYPE(BW::BWGame);
  DUMP_TYPE(BW::PlayerInfo);
  DUMP_TYPE(BW::swishTimer);
  DUMP_TYPE(BW::BWDATA::GameSpeeds);
  DUMP_TYPE(BW::Bitmap);
  DUMP_TYPE(BW::layer);
  DUMP_TYPE(ReplayHeader);
  DUMP_TYPE(BW::unitFinder);
  DUMP_TYPE(BW::TileType);
  DUMP_TYPE(BW::activeTile);
  DUMP_TYPE(BW::MiniTileMaps_type::MiniTileFlagArray);
  DUMP_TYPE(BW::MiniTileMaps_type);
  DUMP_TYPE(BW::SAI_Paths);
  DUMP_TYPE(BW::dlgEvent);
  DUMP_TYPE(BW::CUnit);
  DUMP_TYPE(BW::CBullet);
  DUMP_TYPE(BW::CSprite);
  DUMP_TYPE(BW::CImage);
  DUMP_TYPE(BW::CThingy);
  DUMP_TYPE(BW::COrder);
  DUMP_TYPE(BW::CAIController);
  DUMP_TYPE(BW::Target);
  DUMP_TYPE(BW::UnitTarget);
  DUMP_TYPE(BW::PositionUnitTarget);
  DUMP_TYPE(BW::Path);
  DUMP_TYPE(BW::pathPoint);
  DUMP_TYPE(BW::pathBox);
  DUMP_TYPE(BW::pathRect);
  DUMP_TYPE(BW::region);
  DUMP_TYPE(BW::split);
  DUMP_TYPE(BW::contour);
  DUMP_TYPE(BW::contourHub);
  DUMP_TYPE(BW::Font);
  DUMP_TYPE(BW::FontChar);
  DUMP_TYPE(BW::grpHead);
  DUMP_TYPE(BW::grpFrame);
  DUMP_TYPE(BW::dialog);
  DUMP_TYPE(BW::Triggers::Trigger);
  DUMP_TYPE(BW::Triggers::Condition);
  DUMP_TYPE(BW::Triggers::Action);
  DUMP_TYPE(BW::BWGame::TriggerLocation);
  DUMP_TYPE(BW::pt);
  DUMP_TYPE(BW::bounds);
  DUMP_TYPE(BW::BWGame::Counts);
  DUMP_TYPE(BW::BWGame::SuppliesPerRace);
  DUMP_TYPE(BW::BWGame::Selection);
  DUMP_TYPE(BW::BWGame::Selection::UnitGroup);
  DUMP_TYPE(BW::Town);
  DUMP_TYPE(BW::townQueueEntry);
  DUMP_TYPE(BW::VCList<BW::Triggers::Trigger>);
  DUMP_TYPE(BW::VCListEntry<BW::Triggers::Trigger>);
  DUMP_TYPE(BW::TileSet);
  DUMP_TYPE(ReplayHeader::_gameSeed);
  DUMP_TYPE(ReplayHeader::_netGame::_gameTemplate);
  DUMP_TYPE(ReplayHeader::_netGame);
  DUMP_TYPE(ReplayHeader::_playerEntry);
  DUMP_TYPE(POINT);
  DUMP_TYPE(PALETTEENTRY);
  DUMP_TYPE(RECT);

  std::printf("\n# --- addresses each BWDATA reference is bound to ---\n");
  DUMP_ADDR(Game);
  DUMP_ADDR(PlayerVictory);
  DUMP_ADDR(Players);
  DUMP_ADDR(PlayerDownloadStatus);
  DUMP_ADDR(playerStatusArray);
  DUMP_ADDR(ReplayVision);
  DUMP_ADDR(ReplayRevealAll);
  DUMP_ADDR(commonSwishControllers);
  DUMP_ADDR(gluCustmSwishController);
  DUMP_ADDR(gluCmpgnSwishController);
  DUMP_ADDR(gluScoreSwishController);
  DUMP_ADDR(gluChatSwishController);
  DUMP_ADDR(sgdwBytesInCmdQueue);
  DUMP_ADDR(TurnBuffer);
  DUMP_ADDR(GameSpeedModifiers);
  DUMP_ADDR(GameSpeed);
  DUMP_ADDR(LatencyFrames);
  DUMP_ADDR(FrameSkip);
  DUMP_ADDR(Latency);
  DUMP_ADDR(DialogList);
  DUMP_ADDR(FontBase);
  DUMP_ADDR(GameScreenBuffer);
  DUMP_ADDR(GamePalette);
  DUMP_ADDR(DDInterface);
  DUMP_ADDR(PrimaryPalette);
  DUMP_ADDR(PrimarySurface);
  DUMP_ADDR(BackSurface);
  DUMP_ADDR(ScreenLayers);
  DUMP_ADDR(UnitNodeList_VisibleUnit_First);
  DUMP_ADDR(UnitNodeList_HiddenUnit_First);
  DUMP_ADDR(UnitNodeList_ScannerSweep_First);
  DUMP_ADDR(UnitNodeTable);
  DUMP_ADDR(BulletNodeTable_FirstElement);
  DUMP_ADDR(BulletNodeTable);
  DUMP_ADDR(UnitOrderingX);
  DUMP_ADDR(UnitOrderingY);
  DUMP_ADDR(UnitOrderingCount);
  DUMP_ADDR(gameType);
  DUMP_ADDR(InReplay);
  DUMP_ADDR(NetMode);
  DUMP_ADDR(ReplayHead);
  DUMP_ADDR(GameState);
  DUMP_ADDR(gwNextGameMode);
  DUMP_ADDR(gwGameMode);
  DUMP_ADDR(glGluesMode);
  DUMP_ADDR(g_LocalHumanID);
  DUMP_ADDR(customList_UIDlgData);
  DUMP_ADDR(ClientSelectionGroup);
  DUMP_ADDR(ClientSelectionCount);
  DUMP_ADDR(InputProcedures);
  DUMP_ADDR(EventDialogs);
  DUMP_ADDR(InputFlags);
  DUMP_ADDR(isGamePaused);
  DUMP_ADDR(MoveToX);
  DUMP_ADDR(MoveToY);
  DUMP_ADDR(Mouse);
  DUMP_ADDR(ScreenX);
  DUMP_ADDR(ScreenY);
  DUMP_ADDR(CurrentMapFolder);
  DUMP_ADDR(SaveGameFile);
  DUMP_ADDR(TriggerVectors);
  DUMP_ADDR(MapTileArray);
  DUMP_ADDR(TileSetMap);
  DUMP_ADDR(MiniTileFlags);
  DUMP_ADDR(ActiveTileArray);
  DUMP_ADDR(SAIPathing);

  return 0;
}
